[package]
name = "km_common"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = "0.9.9"
prost = "0.13"
uuid = { version = "1.20.0", features = ["v4", "serde"] }
zeroize = { version = "1.8.2", features = ["derive"] }

[build-dependencies]
prost-build = "0.13"
protoc-bin-vendored = "3.2.0"
