[package]
name = "ws_key_custody_core"
version = "0.1.0"
edition = "2024"

[dependencies]
km_common = { path = "../../km_common" }
uuid = { version = "1.20.0", features = ["v4"] }
zeroize = "1.8"
prost = "0.13"
